#!/usr/bin/env python3
# This program finds all names that are the same in the top 10 names of two countries with a given gender and given year
import sys
import csv
import pandas as pd

country1 = "alberta"
country2 = "california"
gender = "males"
year = 1975
total = 0
country1Names = []
country2Names = []
commonNames = []

with open("./", country1, "/", country1, gender.title()) as csvDataFile:
    next(csvDataFile)
    csvReader = csv.reader(csvDataFile, delimiter=",")
    for row in csvReader:
        if (int(row[1]) == year) and total < 10:
            country1Names.append(row[2])
            total += 1
total = 0
with open("./", country2, "/", country2, gender.title()) as csvDataFile:
    next(csvDataFile)
    csvReader = csv.reader(csvDataFile, delimiter=",")
    for row in csvReader:
        if (int(row[1]) == year) and total < 10:
            country2Names.append(row[2])
            total += 1
total = 0
for i in range(10):
    if country1Names[i] == country2Names[i]:
        commonNames.append(country1Names[i])
        total += 1
